### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by vitorgamer58** [gravio-net/graviex#1]
i get this erro
```
deploy@vultr:~/graviex/graviex-exchange$ bundle exec rake assets:precompile
rake aborted!
Grape::Exceptions::IncompatibleOptionValues: default: giobtc is incompatible with values: ["btccny", "all"]
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/grape-0.7.0/lib/grape/validations.rb:239:in `validates'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/grape-0.7.0/lib/grape/validations.rb:129:in `optional'
/home/deploy/graviex/graviex-exchange/app/api/api_v2/orders.rb:10:in `block in <class:Orders>'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/grape-0.7.0/lib/grape/validations.rb:97:in `instance_eval'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/grape-0.7.0/lib/grape/validations.rb:97:in `initialize'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/grape-0.7.0/lib/grape/validations.rb:290:in `new'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/grape-0.7.0/lib/grape/validations.rb:290:in `params'
/home/deploy/graviex/graviex-exchange/app/api/api_v2/orders.rb:8:in `<class:Orders>'
/home/deploy/graviex/graviex-exchange/app/api/api_v2/orders.rb:2:in `<module:APIv2>'
/home/deploy/graviex/graviex-exchange/app/api/api_v2/orders.rb:1:in `<top (required)>'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:330:in `require_or_load'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:463:in `load_missing_constant'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:184:in `const_missing'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:495:in `load_missing_constant'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:184:in `const_missing'
/home/deploy/graviex/graviex-exchange/app/api/api_v2/mount.rb:32:in `<class:Mount>'
/home/deploy/graviex/graviex-exchange/app/api/api_v2/mount.rb:5:in `<module:APIv2>'
/home/deploy/graviex/graviex-exchange/app/api/api_v2/mount.rb:4:in `<top (required)>'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:330:in `require_or_load'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:463:in `load_missing_constant'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:184:in `const_missing'
/home/deploy/graviex/graviex-exchange/config/routes.rb:132:in `block in <top (required)>'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.12/lib/action_dispatch/routing/route_set.rb:337:in `instance_exec'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.12/lib/action_dispatch/routing/route_set.rb:337:in `eval_block'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.12/lib/action_dispatch/routing/route_set.rb:315:in `draw'
/home/deploy/graviex/graviex-exchange/config/routes.rb:9:in `<top (required)>'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `block in load'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:40:in `each'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/file_update_checker.rb:75:in `call'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/file_update_checker.rb:75:in `execute'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application/routes_reloader.rb:6:in `execute_if_updated'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `instance_exec'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `run'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:54:in `run_initializers'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:215:in `initialize!'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/deploy/graviex/graviex-exchange/config/environment.rb:5:in `<top (required)>'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:189:in `require_environment!'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:260:in `block in run_tasks_blocks'
/home/deploy/graviex/graviex-exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
/home/deploy/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/home/deploy/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
Tasks: TOP => environment
```

**Comment by ghost** [comment]
Look up `giobtc` in `orders.rb` and change it up to fit your primary market.

**Comment by vitorgamer58** [comment]
ok

**Comment by vitorgamer58** [comment]
Where can I find the `orders.rb` file?

**Comment by vitorgamer58** [comment]
https://github.com/gravio-net/graviex/blob/master/app/api/api_v2/orders.rb
Find and Solved

**Comment by anhbaysgalan1** [comment]
Hello guys i replaced and modified orders.rb but i have taking this error any solutions ?
