### ISSUE TITLE
deposit is not working

### ISSUE THREAD

**Issue by pankaj9310** [gravio-net/graviex#3]
Hi Team
I have configured this exchange. I have done deposit ETH but eth balance is not showing in my funds page and  Deposit history is also empty.
In admin panel I can see the ETH balance. 
What is the problem Can you help me to fix.
Thanks

**Comment by mochfauz** [comment]
walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}' 
Don't forget to put on your wallet conf. 

Had you configure it all? 

I have a little question, I get this little error when installing this scrypt. 
Here is my error:
![image](https://user-images.githubusercontent.com/37583175/41431862-7c7676bc-703e-11e8-9e6b-4a43706c5278.png)

**Comment by dagnyc** [comment]
> walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'
> Don't forget to put on your wallet conf.
> 
> Had you configure it all?
> 
> I have a little question, I get this little error when installing this scrypt.
> Here is my error:
> ![image](https://user-images.githubusercontent.com/37583175/41431862-7c7676bc-703e-11e8-9e6b-4a43706c5278.png)

Did you ever figure this out? I have a similar issue. My deposits can be seen in the user's deposit history but the deposit never updates the confirmations. Just always stuck at 0 confirmations. I get error message: 

Error on PaymentTransaction::Normal: undefined local variable or method `c' for #<Deposits::Mobitglobal:0x00557a2369aff8>
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/activemodel-4.0.12/lib/active_model/attribute_methods.rb:439:in `method_missing'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/attribute_methods.rb:168:in `method_missing'

**Comment by pblab-dev** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
